<img src="https://github.com/EDGE-Programe/Python-Basics/blob/master/Python_edge_program/logo_images/NumPy_logo_2020.png?raw=1" alt="NumPy Logo" width=70% height=70% title="NumPy Logo">

### What is NumPy?

NumPy is a powerful Python library for numerical computing. It stands for "Numerical Python." It provides a high-performance multidimensional array object called ndarray, along with a collection of functions for performing array operations, mathematical computations, and data manipulation.<br>

### Where is NumPy used?

NumPy is widely used in various domains and applications that involve numerical computing, scientific research, data analysis, and machine learning. Here are some areas where NumPy finds extensive usage:<br>

**1. Scientific Research:** NumPy is a fundamental tool in scientific research and computational science. It is used in areas such as physics, chemistry, biology, astronomy, and engineering for data analysis, simulations, and mathematical modeling.<br>

**2. Data Analysis:** NumPy is an essential library in data analysis workflows. It provides efficient data structures for handling large datasets and enables fast numerical computations. NumPy is often used in conjunction with Pandas, another popular data manipulation library, to process and analyze structured data.<br>

**3.Machine Learning:** NumPy serves as a foundation for many machine learning frameworks and libraries. It provides the data structures and mathematical functions required for performing operations on arrays, such as preprocessing data, feature extraction, matrix operations, and model evaluation.<br>

**4.Image and Signal Processing:** NumPy is extensively used in image processing and digital signal processing tasks. It allows for efficient manipulation and analysis of image and audio data through operations like filtering, convolution, Fourier transforms, and image transformations.<br>

**5.Simulation and Modeling:** NumPy is used in simulations and modeling applications to generate and manipulate large sets of random data, simulate physical systems, solve differential equations, and analyze the results of simulations.<br>

**6.Optimization and Numerical Analysis:** NumPy provides tools and functions for optimization problems, numerical integration, interpolation, solving linear and nonlinear equations, and other numerical analysis tasks.<br>

**7.Visualization:** NumPy integrates seamlessly with visualization libraries such as Matplotlib and Seaborn, allowing for the creation of informative and visually appealing plots and charts to visualize data and results.<br>

**8.Financial and Econometric Analysis:** NumPy is employed in financial analysis and econometrics for tasks such as time series analysis, risk management, option pricing, and portfolio optimization.<br>

**These are just a few examples of the many areas where NumPy is used. Its efficient array operations, extensive mathematical functions, and integration with other scientific computing libraries make it a versatile tool for a wide range of applications involving numerical computations and data analysis.**<br>

### Installing the NumPy Module

**You can find latest verison & older of any python package on [PyPi:Python Package Index](https://pypi.org/)**

In [ ]:
! pip install numpy

**In Jupyter notebooks, the exclamation mark `(!)` is used to execute console commands or shell commands directly from within a notebook cell. It allows you to run commands as if you were executing them in a command-line interface or terminal.**<br>

### The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.<br>

For example, the array for the coordinates of a point in 3D space, `[1, 2, 1]`, has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.<br>

```
[[1., 0., 0.],
 [0., 1., 2.]]
 ```

NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality.<br>

<img src="https://github.com/EDGE-Programe/Python-Basics/blob/master/Python_edge_program/logo_images/numpy_arrays.png?raw=1" alt="NumPy" width=70% height=70% title="NumPy Logo">

### NumPy Array Creation & It's Attributes

There are several ways to create arrays.<br>

For example, you can create an `array` from a regular Python **`list`** or **`tuple`** using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.<br>

In [ ]:
import numpy as np # Importing the NumPy package

In [ ]:
a = np.array([2, 3, 4])
print(a)

[2 3 4]


In [ ]:
a_list = [2,3,4]
print(type(a_list))

<class 'list'>


In [ ]:
a = np.array(a_list)
print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


There are some important attributes of an `ndarray` object. They are:<br>

**ndarray.ndim**
 - the number of axes (dimensions) of the array.<br>

**ndarray.shape**
 - the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`.<br>

**ndarray.size**
   - the total number of elements of the array. This is equal to the product of the elements of `shape`.<br>
   
**ndarray.dtype**
   - an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.<br>
   
**ndarray.data**
   - the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.<br>


In [ ]:
print(a.shape) # shape(rows,columns) of the numpy array 'a'

(3,)


In [ ]:
print(a.size) # number of elements in numpy array 'a'

3


In [ ]:
print(a.ndim) # number of dimensions in numpy array 'a'

1


In [ ]:
print(a.dtype) # type of data inside the numpy array 'a'

int64


**A frequent error consists in calling `array` with multiple arguments, rather than providing a single sequence as an argument.**<br>

```python
a = np.array(1, 2, 3, 4)    # WRONG
```

In [ ]:
a = np.array([1, 2, 3, 4])    # RIGHT

#### NumPy.empty()
The **`empty()`** function creates an array without initializing its elements, resulting in random or garbage values.

In [ ]:
# Create an empty 1-dimensional array
empty_array_1d = np.empty(5)
print(empty_array_1d)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
# Create an empty 2-dimensional array
empty_array_2d = np.empty((3, 4))
print(empty_array_2d)

[[3. 7. 3. 4.]
 [1. 4. 2. 2.]
 [7. 2. 4. 9.]]


In the above example, **`np.empty(5)`** creates a **`1-dimensional`** array of **`size 5`** with uninitialized elements. Similarly, **`np.empty((3, 4))`** creates a **`2-dimensional`** array with **`3`** rows and **`4`** columns, again with uninitialized elements.

#### NumPy.full()
The **`np.full()`** function creates a new array with a specified shape and fills it with a specified value.

**Syntax:**

```python
np.full(shape, fill_value, dtype)
```

In [ ]:
# Create a 3x3 array filled with 5
arr_full = np.full((3, 3), 5)
print(arr_full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


#### NumPy.zeros()
The **`np.zeros()`** function creates a new array with a specified shape and initializes all elements to **`0`**.

In [ ]:
# Create a 2x4 array filled with zeros
arr_zeros = np.zeros((2, 4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### NumPy.ones()
The **`np.ones()`** function creates a new array with a specified shape and initializes all elements to 1.

**Syntax:**
```python
np.ones(shape, dtype, order)
```

In [ ]:
# Create a 3x2 array filled with ones
arr_ones = np.ones((3, 2), dtype="int64")
print(arr_ones)

[[1 1]
 [1 1]
 [1 1]]


#### NumPy.arrange()

**`np.arange()`** function is used to create an array with regularly spaced values within a specified range. It returns an array that contains a sequence of numbers based on the start, stop, and step size provided as arguments.<br>

The syntax of `np.arange()` is as follows:
```python
np.arange(start, stop, step)
```

**start (optional):** The starting value of the sequence. If not specified, the default value is 0.<br>

**stop:** The end value of the sequence. The generated sequence will contain values up to, but not including, this value.<br>

**step (optional):** The step size or increment between consecutive values. If not specified, the default value is 1.<br>

In [ ]:
# Create an array with values from 0 to 9 (exclusive)
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Create an array with values from 2 to 10 (exclusive) with a step size of 2
arr = np.arange(2, 10, 2)
print(arr)

[2 4 6 8]


#### NumPy.random.rand()

**`np.random.rand()`** is used to generate an array of random values from a uniform distribution over the range **`[0, 1]`**.

In [ ]:
# Generate a random value between 0 and 1
random_value = np.random.rand()
print(random_value)

0.6744690939944485


In [ ]:
# Generate a 1D array with 5 random values
array_1d = np.random.rand(5)
print(array_1d)

[0.46271326 0.63715952 0.76690281 0.43970738 0.79850958]


In [ ]:
# Generate a 2D array with dimensions 2x3
array_2d = np.random.rand(2, 3)
print(array_2d)

[[0.19662599 0.8982319  0.01796172]
 [0.96994819 0.96037439 0.70342396]]


### Multi-Dimensional Array Creation

**`NumPy array`** transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.<br>

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5.8, 6)]) # 'b' is a multi-dimensional numpy array

In [ ]:
print(b.ndim)

2


In [ ]:
print("shape of arrayb",b.shape) # (rows,columns) in numpy array 'b'
print("size of array b:",b.size) # elements in numpy array 'b'

shape of arrayb (2, 3)
size of array b: 6


In [ ]:
print(b.dtype) # numpy array 'b' is in 'float64' datatype

float64


**This is because array contains elements 1.5 and 5.8 which are floating point numbers;
which is why every element is converted into float(as to create a numpy array every
element has to be same data-type). So, 2 becomes 2., 3 becomes 3. and so on.<br>**

In [ ]:
print(b)

[[1.5 2.  3. ]
 [4.  5.8 6. ]]


#### The type of the array can also be explicitly specified at creation time:<br>

In [ ]:
b = np.array([(1.5, 2, 3), (4, 5.8, 6)], dtype='float32')

In [ ]:
print(b)
print(b.dtype)

[[1.5 2.  3. ]
 [4.  5.8 6. ]]
float32


#### Reshaping Arrays

In [ ]:
print(b.shape)
b = b.reshape(3,2) # changing the shape (row,column) of numpy array 'b'
print(b.shape)
print(b)

(2, 3)
(3, 2)
[[1.5 2. ]
 [3.  4. ]
 [5.8 6. ]]


**The total number of elements in the original array must be equal to the total number of elements in the reshaped array. In other words, the sizes must be compatible. For example, an array with 12 elements can be reshaped into a shape of (3, 4) or (6, 2), as both result in an array with 12 elements.<br>**

In [ ]:
b = b.reshape(6,1) # row = 6 (number of rows), column = 1 (number of elements in each row)
print(b.shape)
print(b)

(6, 1)
[[1.5]
 [2. ]
 [3. ]
 [4. ]
 [5.8]
 [6. ]]


### Basic Arithmetic Operations

In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [ ]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a + b # adding each positional elements of array 'a' with elements of array 'a'
print(c)

[20 31 42 53]


In [ ]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b # subtracting each positional elements of array 'a' with elements of array 'a'
print(c)

[20 29 38 47]


In [ ]:
b *= 3 # each element of array 'b' will be multiplied by 3
print(b)

[0 3 6 9]


#### Multiplying two numpy arrays
In NumPy, you can multiply two arrays element-wise using the * operator. The * operator performs element-wise multiplication when used with NumPy arrays.<br>

In [ ]:
# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Multiply the arrays element-wise
result = a * b
print(result)

[ 4 10 18]


Note that the arrays being multiplied **`must have compatible shapes`**, meaning they should either have the **`same shape`** or **`broadcastable shapes`** as per the NumPy broadcasting rules. If the arrays have different shapes, NumPy will try to broadcast them to perform element-wise multiplication.<br>

#### Matrix Multiplication
If you want to perform matrix multiplication (dot product) instead of element-wise multiplication, you can use the np.dot() function.<br>

![dot multiplication](logo_images/dot.svg "Dot Multiplication")

In [ ]:
# Create two arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In order to perform the **`dot`** product **(matrix multiplication)** between two NumPy arrays, the number of columns in the first array must be equal to the number of rows in the second array. This ensures that the shapes of the arrays are compatible for matrix multiplication.<br>

Array **`'a'`** of **`shape(m,n)`** can be have a **`dot`** product with another array of shape(n,p).<br>
New array will have the **`shape(m,p)`**.<br>

In [ ]:
# Create two arrays with compatible shapes
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = np.array([[7, 8], [9, 10], [11, 12]])  # Shape: (3, 2)

# Perform dot product (matrix multiplication)
result = np.dot(a, b)
print(result)
print(result.shape)

[[ 58  64]
 [139 154]]
(2, 2)


### Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” **`(ufunc)`**. Within NumPy, these functions operate elementwise on an array, producing an array as output.<br>

**`np.sqrt()`** & **`np.add()`**

In [ ]:
a = np.arange(3)
print(a)

b = np.sqrt(a) # np.sqrt() function applies square root on each element of array 'b'
print(b)

c = np.add(a,b) # adds each positional elements of array 'a' and array 'b'
print(c)

[0 1 2]
[0.         1.         1.41421356]
[0.         2.         3.41421356]


**`np.average()`** function is used to calculate the weighted average of elements in an array. It can be used to compute the arithmetic mean, taking into account the weights assigned to each element.<br>

In [ ]:
a = np.arange(10)
b = np.average(a) # calculates average element value in a numpy array
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
4.5


In [ ]:
a = np.array([[7, 8], [9, 10], [11, 12]])
b = np.average(a)
print(a)
print(b)

[[ 7  8]
 [ 9 10]
 [11 12]]
9.5


**`np.where()`** function is used to return elements from one of two arrays based on a specified condition. It is a powerful tool for array indexing and conditional operations.<br>

In [ ]:
# Create an array
a = np.array([1, 2, 3, 4, 5])

# Create a condition
condition = (a < 3)

# Use np.where() to select elements based on the condition
result = np.where(condition, a, 10)

print(result)

[ 1  2 10 10 10]


In this example, we have an array **`a`** with the elements **`[1, 2, 3, 4, 5]`**. We create a condition condition where we check if each element of **`a`** is less than **`3`**. By using **`np.where(condition, a, 10)`**, we select elements from arr where the condition is **`True`**, and elements from the scalar value **`10`** where the condition is **`False`**. The resulting array result contains **`[1, 2, 10, 10, 10]`**.<br>

The condition argument in **`np.where()`** specifies the condition that is evaluated element-wise. If the condition is **`True`** for an element, the corresponding element from the **`x`** array is selected; otherwise, the corresponding element from the **`y`** array is selected.<br>

The **`x`** and **`y`** arguments can be arrays, scalars, or a combination of both. When arrays are provided, they should have compatible shapes to enable element-wise selection.<br>

The **`np.where()`** function is versatile and can be used for a wide range of applications, including data filtering, conditional assignment, and array transformations based on specific conditions.

#### More Universal Functions

**`all`, `any`, `apply_along_axis`, `argmax`, `argmin`, `argsort`, `average`, `bincount`, `ceil`, `clip`, `conj`, `corrcoef`, `cov`, `cross`, `cumprod`, `cumsum`, `diff`, `dot`, `floor`, `inner`, `invert`, `lexsort`, `max`, `maximum`, `mean`, `median`, `min`, `minimum`, `nonzero`, `outer`, `prod`, `re`, `round`, `sort`, `std`, `sum`, `trace`, `transpose`, `var`, `vdot`, `vectorize`**

### Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.<br>

In [ ]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
a[:6:2] = 1000 # from start to position 6, exclusive, set every 2nd element to 1000
print(a)

[1000    1 1000   27 1000  125  216  343  512  729]


In [ ]:
b = a[2:5] # b contains elements of array from index 2 to 5
print(b)

[1000   27 1000]


In [ ]:
c = a[::-1] # 'c' contains every element of 'a' but in resverse order (from -1(last position) to first)
print(c)

[ 729  512  343  216  125 1000   27 1000    1 1000]


**Iterating over multidimensional arrays is done with respect to the first axis**

In [ ]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


However, if one wants to perform an operation on each element in the array, one can use the **`.flat`** attribute which is an iterator over all the elements of the array.<br>

In [ ]:
for element in c.flat:
    print(element)

0
1
2
10
12
13
100
101
102
110
112
113


### Shape Manipulation

An array has a shape given by the number of elements along each axis.<br>

In [ ]:
a = np.array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

print(a.shape)

(3, 4)


The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array unless you assing the result to original array.<br>

In [ ]:
print(a.flatten()) # returns the array 'a', but flattened

[3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]


In [ ]:
print(a.reshape(6, 2)) # returns the array with a modified shape

[[3. 7.]
 [3. 4.]
 [1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]


In [ ]:
print(a.T) # returns the tranpose of the array 'a'

# or

print(np.transpose(a)) # returns the tranpose of the array 'a'

[[3. 1. 7.]
 [7. 4. 2.]
 [3. 2. 4.]
 [4. 2. 9.]]
[[3. 1. 7.]
 [7. 4. 2.]
 [3. 2. 4.]
 [4. 2. 9.]]


<img src="https://github.com/EDGE-Programe/Python-Basics/blob/master/Python_edge_program/logo_images/transpose.png?raw=1" alt="Numpy Transpose" width=41% height=41% title="Transpose a NumPy Array">

In [ ]:
print(a.shape) # current shape of array 'a'

(3, 4)


**Note:** The **`reshape`** function returns its argument with a modified shape, whereas the **`ndarray.resize`** method modifies the array itself.

#### NumPy.resize()

In [ ]:
a = np.array([[3., 7., 3., 4.],
           [1., 4., 2., 2.],
           [7., 2., 4., 9.]])

a.resize((2, 6)) # resizing the array 'a'

In [ ]:
print(a)
print(a.shape)

[[3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]
(2, 6)


#### NumPy.reshape()

In [ ]:
a = np.array([[3., 7., 3., 4.],
           [1., 4., 2., 2.],
           [7., 2., 4., 9.]])

print(a.shape, "Shape of Array a")
a.reshape((2, 6))

(3, 4) Shape of Array a


array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [ ]:
print(a.shape) # original shape remains the same

(3, 4)


### NumPy.expand_dims()

In NumPy, the **`expand_dims()`** function is used to expand the dimensions of an array. It is used to increase the dimensionality of an existing array by inserting a new axis at a specified position.

The syntax of the **`expand_dims()`** function is as follows:
```python
numpy.expand_dims(arr, axis)
```
In NumPy, axes are **`zero-indexed`**, meaning the first axis is referred to as **`axis 0`**, the **`second axis`** is **`axis 1`**, and so on. The **`negative indexing`** allows you to refer to axes from the **`end`**, where **`-1`** represents the **`last`** axis, **`-2`** represents the **`second-to-last axis`**, and so forth.

In [ ]:
arr = np.array([1, 2, 3])
print(arr.shape)

(3,)


In [ ]:
# Expanding dimensions along axis 0
expanded_arr = np.expand_dims(arr, axis=0)
print(expanded_arr.shape)

(1, 3)


In [ ]:
# Expanding dimensions along axis 1
expanded_arr = np.expand_dims(arr, axis=1)
print(expanded_arr.shape)

(3, 1)


In this example, we have an **`input`** array arr of **`shape (3,)`** containing the numbers **`1, 2, and 3`**. We use **`expand_dims()`** to expand the dimensions along **axis=0** and **axis=1**. The resulting arrays have shapes **`(1, 3)`** and **`(3, 1)`**, respectively.

In [ ]:
# Expanding dimensions along axis -1
expanded_arr = np.expand_dims(arr, axis=-1)
print(expanded_arr.shape)

(3, 1)


The reason **`axis 1`** and **`-1`** are the same is because **`axis -1`** refers to the last axis, and when you have a **`2-dimensional`** array, the second axis is indeed the last axis. Therefore, **`axis 1`** and **`-1`** point to the same axis in the context of a **`2-dimensional`** array.

### NumPy.squeeze()
np.squeeze is a NumPy function that removes single-dimensional entries from the shape of an array. It is used to reduce the dimensionality of an array by collapsing any axes with a **`size of 1`**.

Here's the syntax of **np.squeeze():**

```python
numpy.squeeze(a, axis=None)
```

**`Parameters:`**
- **a:** The input array.
- **axis** (optional): An integer or tuple of integers specifying the axes to squeeze. Default is None, which squeezes all single-dimensional entries.

The **`np.squeeze`** function returns a new array with the same data as the input array but with dimensions of **`size 1 removed`**.

In [ ]:
# Create a 1D array with a single dimension of size 1
a = np.array([[5]])
print("Original Array:")
print(a)
print("Original Shape:", a.shape)

Original Array:
[[5]]
Original Shape: (1, 1)


In [ ]:
# Squeeze the array to remove the single dimension
b = np.squeeze(a)
print("Squeezed Array:")
print(b)
print("Squeezed Shape:", b.shape)

Squeezed Array:
5
Squeezed Shape: ()


In [ ]:
# Squeeze the array in axis=0 to remove the single dimension in first axis
b = np.squeeze(a, axis=0)
print("Squeezed Array:")
print(b)
print("Squeezed Shape:", b.shape)

Squeezed Array:
[5]
Squeezed Shape: (1,)


### Stacking together different arrays
Several arrays can be stacked together along different axes.<br>

In [ ]:
a = np.array([[9., 7.],
              [5., 2.]])

b = np.array([[1., 9.],
              [5., 1.]])

In [ ]:
c = np.vstack((a,b)) # vertically stacks array 'a' and array 'b'

print(c)

[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]]


In [ ]:
d = np.hstack((a,b)) # horizontally stacks array 'a' and array 'b'

print(d)

[[9. 7. 1. 9.]
 [5. 2. 5. 1.]]


The function **`column_stack`** stacks **`1D`** arrays as columns into a **`2D`** array. It is equivalent to **`hstack`** only for **`2D arrays`**.<br>

In [ ]:
a = np.array([4., 2.])

b = np.array([3., 8.])

c = np.column_stack((a, b))

d = np.hstack((a, b))

In [ ]:
print(c)
print("Dimension:",c.ndim)

[[4. 3.]
 [2. 8.]]
Dimension: 2


In [ ]:
print(d)
print("Dimension:",d.ndim)

[4. 2. 3. 8.]
Dimension: 1


On the other hand, the function **`row_stack`** is equivalent to **`vstack`** for any input arrays. In fact, **`row_stack`** is an **`alias`** for **`vstack`.** <br>

### NumPy Array Vs Tensor

NumPy arrays are a general-purpose multidimensional array structure used in numerical computing, while tensors are higher-dimensional arrays often used in deep learning frameworks. Tensors provide additional functionalities specifically tailored for deep learning tasks, such as automatic differentiation and computation graphs. NumPy arrays serve as a foundational data structure underlying many numerical computing operations, including those in deep learning libraries.
<img src="https://github.com/EDGE-Programe/Python-Basics/blob/master/Python_edge_program/logo_images/tensor.png?raw=1" alt="Tensor" width=67% height=67% title="Tensor Object">

### Questions on NumPy Array

   - How to create an empty and a full NumPy array?
   - Create a Numpy array filled with all zeros
   - Create a Numpy array filled with all ones
   - Check whether a Numpy array contains a specified row
   - How to Remove rows in Numpy array that contains non-numeric values?
   - Find the number of occurrences of a sequence in a NumPy array
   - Find the most frequent value in a NumPy array
   - Combining a one and a two-dimensional NumPy Array
   - How to build an array of all combinations of two NumPy arrays?
   - How to compare two NumPy arrays?
   - How to check whether specified values are present in NumPy array?
   - How to get all 2D diagonals of a 3D NumPy array?
   - Flatten a Matrix in Python using NumPy
   - Flatten a 2d numpy array into 1d array
   - Move axes of an array to new positions
   - Interchange two axes of an array
   - Counts the number of non-zero values in the array
   - Count the number of elements along a given axis
   - Change data type of given numpy array
   - Reverse a numpy array